---
apiVersion: v2
version: 0.19.3
appVersion: "0.19.1"
description: Provides easy redis setup definitions for Kubernetes services, and deployment.
engine: gotpl
maintainers:
  - name: muhammadqadora
name: redis-operator
sources:
  - https://github.com/falkordb/redis-operator
home: https://github.com/falkordb/operator
keywords:
- operator
- redis
- opstree
- kubernetes
- openshift
