---
apiVersion: v2
version: 0.1.0
appVersion: "0.19.1"
description: Provides easy falkordb-operator setup definitions for Kubernetes services, and deployment.
engine: gotpl
maintainers:
  - name: muhammadqadora
name: operator
sources:
  - https://github.com/falkordb/operator
home: https://github.com/falkordb/operator
keywords:
- operator
- redis
- opstree
- kubernetes
- openshift
