apiVersion: v2
name: cluster
description: Provides easy redis setup definitions for Kubernetes services, and deployment.
version: 0.16.7
appVersion: "0.16.5"
home: https://github.com/falkordb/operator
sources:
  - https://github.com/falkordb/operator
maintainers:
  - name: muhammadqadora
keywords:
- operator
- redis
- opstree
- kubernetes
- openshift
- redis-exporter
type: application
