name: Build Docker Image for Operator testing
on:
  pull_request:
    types: [opened, synchronize, ready_for_review]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for the image'
        required: true
        default: 'latest'

env:
  REPOSITORY: falkordb/operator
jobs:
  build_scan_container_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
              
      - name: Build multi-arch image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm64,linux/amd64
          push: true
          tags: |
            ${{ env.REPOSITORY }}:${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.ref_name }}
            ${{ env.REPOSITORY }}:latest